spring.application.name=SpringCRUD

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JDBC logging
logging.level.org.springframework.jdbc.core=DEBUG

logging.level.org.springframework=DEBUG
logging.level.com.example=DEBUG